### ISSUE TITLE
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

### ISSUE THREAD

**Issue by tao-bai** [ianmcdiarmidsterling/adversarial#1]
something wrong when i attempted to run your codes. Could you please help?

The error occurred here. I guess it is because of the output of yolov3. 
```
File "adversarial_attack.py", line 387, in generate_attack
    conf_loss.backward()
```

**Comment by IMSterling** [comment]
I just verified that the repository is correct.

Have you changed any of the code?
Did you clone the entire repo?
Did you change the config.gin file?


Happy to help but need more information.

Ian

**Comment by tao-bai** [comment]
I changed a little. I had problems loading models, so I changed the model and loaded it successfully, which is from https://github.com/ultralytics/yolov3. Then I met the above problems.

**Comment by IMSterling** [comment]
Closed (time)
